# -*- coding: utf-8 -*-
"""while_for.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jqg-FTWe0PNgZWvxFQAsJADln1Gk9YMy
"""

for i in range (0, 10):
  if i % 2 == 0:
    continue
  print(i)

for i in range (1, 6):
  continue
print(i)

# output 5
i = 1
while i <= 5:
  print(i)
  i += 1

i = 0
while i < 5:
  i += 1
  if i == 3:
    continue
  print(i)

user_num = int(input("Enter the Number in Range (10 - 50): "))
numbers = [10, 20, 30, 40, 50]

if user_num in numbers:
  print(f"Number found: {user_num}")
else:
  print("Number not found!")

for i in range (1, 11):
  if i % 2 == 0:
    continue
  print(i)

i = 0
while i <= 19:
  i += 1
  print(i)

i = 2
while i <= 28:
  i += 2
  print(i)

i = 51
while i >= 1:
  i -= 1
  print(i)

num = input("enter number")
n = int(num)
sum = 0
for i in range (1, n + 1):
  sum += i
print(sum)

n = input("enter")

